# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: iot-deployment
serviceName: iot
appLabel: iot
appName: iot

replicaCount: 2

image:
  repository: hcorptech/iotservice
  tag: 0.0.1

containerPort: 8086

service:
  type: ClusterIP
  port: 8086
  targetPort: 8086

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

appname_enabled: true
profile_enabled: true
discovery_enable: true
mongo_host_enable: true
jwt_enable: false
