deploymentName: user
serviceName: user
appLabel: user
appName: user
nameOverride: "user"
fullnameOverride: "user"
replicaCount: 1

image:
  repository: hcorptech/userservice
  tag: 0.0.1

containerPort: 8081

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

appname_enabled: true
profile_enabled: true
discovery_enable: true
mongo_host_enable: true
jwt_enable: true
